// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqwqnfjoqsapllctokiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxd3FuZmpvcXNhcGxsY3Rva2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzM1NzUsImV4cCI6MjA2NTU0OTU3NX0.3pba5tfRtM7wy67D_OBX-5WZtHsPUXb8Sds8oxljNZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);